apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancer-prediction
  namespace: cancer-prediction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cancer-prediction-app
  template:
    metadata:
      labels:
        app: cancer-prediction-app
    spec:
      containers:
      - name: cancer-prediction
        image: sahkanu37/cancer_prediction:latest
        ports:
        - containerPort: 8501 
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"