apiVersion: v1
kind: Service
metadata:
  name: cancer-prediction-service
  namespace: cancer-prediction
spec:
  selector:
    app: cancer-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501  # must match your containerPort
  type: LoadBalancer