apiVersion: v1
kind: Service
metadata:
  name: cancer-prediction-service
  namespace: cancer-prediction
spec:
  selector:
    app: cancer-prediction
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501  
  type: LoadBalancer